# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:41
from __future__ import unicode_literals

import csq_interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csq_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='configfile',
            field=models.FileField(null=True, upload_to=csq_interface.models.config_file_name),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='configtimestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='graphfile',
            field=models.FileField(null=True, upload_to=csq_interface.models.graph_file_name),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='graphtimestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
